version: '3.7'

services:
  parikng_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - parking_network
    volumes:
    - ./DB:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - parking_network

  thing2db:
    build:
      context: ./Thing2DB
      dockerfile: Dockerfile
    image: thing2db
    container_name: thing2db
    depends_on:
      - parikng_database
    ports:
      - 9848:9848
    networks:
      - parking_network
      
  server2client:
    build:
      context: ./Server2Client
      dockerfile: Dockerfile
    image: server
    container_name: server2client
    depends_on:
      - thing2db
    ports:
      - 9849:9849
    networks:
      - parking_network

volumes:
  DB:
    driver: local

networks:
  parking_network:
    name: parking_network
    driver: bridge